# config/universes/topix_core_30_20251031.yaml
# 更新日: 2025-10-31
# 出典: JPX TOPIX Core30 構成銘柄一覧

universe:
  - { code: 2914, name: 日本たばこ産業, ticker: "2914.T" }
  - { code: 3382, name: セブン&アイ・ホールディングス, ticker: "3382.T" }
  - { code: 4063, name: 信越化学工業, ticker: "4063.T" }
  - { code: 4502, name: 武田薬品工業, ticker: "4502.T" }
  - { code: 4568, name: 第一三共, ticker: "4568.T" }
  - { code: 6098, name: リクルートホールディングス, ticker: "6098.T" }
  - { code: 6367, name: ダイキン工業, ticker: "6367.T" }
  - { code: 6501, name: 日立製作所, ticker: "6501.T" }
  - { code: 6503, name: 三菱電機, ticker: "6503.T" }
  - { code: 6758, name: ソニーグループ, ticker: "6758.T" }
  - { code: 6857, name: アドバンテスト, ticker: "6857.T" }
  - { code: 6861, name: キーエンス, ticker: "6861.T" }
  - { code: 7011, name: 三菱重工業, ticker: "7011.T" }
  - { code: 7203, name: トヨタ自動車, ticker: "7203.T" }
  - { code: 7267, name: 本田技研工業, ticker: "7267.T" }
  - { code: 7741, name: HOYA, ticker: "7741.T" }
  - { code: 7974, name: 任天堂, ticker: "7974.T" }
  - { code: 8001, name: 伊藤忠商事, ticker: "8001.T" }
  - { code: 8031, name: 三井物産, ticker: "8031.T" }
  - { code: 8035, name: 東京エレクトロン, ticker: "8035.T" }
  - { code: 8058, name: 三菱商事, ticker: "8058.T" }
  - { code: 8306, name: 三菱UFJフィナンシャル・グループ, ticker: "8306.T" }
  - { code: 8316, name: 三井住友フィナンシャル・グループ, ticker: "8316.T" }
  - { code: 8411, name: みずほフィナンシャル・グループ, ticker: "8411.T" }
  - { code: 8729, name: ソニーフィナンシャルグループ, ticker: "8729.T" }
  - { code: 8766, name: 東京海上ホールディングス, ticker: "8766.T" }
  - { code: 9432, name: NTT, ticker: "9432.T" }
  - { code: 9433, name: KDDI, ticker: "9433.T" }
  - { code: 9434, name: ソフトバンク, ticker: "9434.T" }
  - { code: 9983, name: ファーストリテイリング, ticker: "9983.T" }
  - { code: 9984, name: ソフトバンクグループ, ticker: "9984.T" }